/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package reportdetails;

import java.util.ArrayList;
import java.util.List;

public class ReportManager {
    private final SLList allReports; 
    private final LinkedQueue pendingQueue;
    private final LinkedStack recentReportsStack;
    
    public ReportManager(){
        allReports = new SLList();
        pendingQueue = new LinkedQueue();
        recentReportsStack = new LinkedStack();
    }
    
    public void addReport(Reportable report){
        allReports.add(report);
        
        // Add to queue if status is pending
        if (report instanceof ReportDetails rd) {
            if ("pending".equalsIgnoreCase(rd.getStatus())) {
                pendingQueue.enqueue(report);
            }
        }
        
        // Add to stack (recent reports)
        recentReportsStack.push(report);
    }
    
    public void displayAllReports(){
        allReports.printList();
    }
    
    public Reportable getReport(int position) {
    try {
        Object node = allReports.get(position);
        if (node instanceof SlNode slNode) {
            Object data = slNode.getData();
            if (data instanceof Reportable reportable) {
                return reportable;
            }
        }
    } catch (Exception e) {
        e.printStackTrace(); // This will help us see the error this was generated by AI in particular deepseek and its to help me handle errore 
        return null;
    }
    return null;
}
    
    public void deleteReport(int position){
        try {
            Reportable report = getReport(position);
            if (report != null) {
                allReports.remove(position);
            }
        } catch (Exception e) {
            // Handle error
        }
    }
    
    public void updateReport(int position, Reportable newReport){
        try {
            allReports.remove(position);
            allReports.add(position, newReport);
        } catch (Exception e) {
            // Handle error
        }
    }
    
    public int getSize() {
        return allReports.size();
    }
    
    public List<Reportable> getAllReports() {
        List<Reportable> reportList = new ArrayList<>();
        for (int i = 1; i <= allReports.size(); i++) {
            try {
                Reportable report = getReport(i);
                if (report != null) {
                    reportList.add(report);
                }
            } catch (Exception e) {
                // Skip errors
            }
        }
        return reportList;
    }
    
    public LinkedQueue getPendingQueue() {
        return pendingQueue;
    }
    
    public LinkedStack getRecentReportsStack() {
        return recentReportsStack;
    }
    
    public Object[] getPendingReportsArray() {
        // Convert queue to array without removing elements
        return pendingQueue.toArray();
    }
    
    public Object[] getRecentReportsArray() {
        return recentReportsStack.toArray();
    }
}